spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.taotie.entity
  configuration:
    map-underscore-to-camel-case: true

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} %green([%X{traceId}]) %magenta([%thread]) %-5level %logger{36} : %msg%n"
